// <auto-generated />
using System;
using EGovServices.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EGovServices.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523180859_AddAppointmentFeature")]
    partial class AddAppointmentFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EGovServices.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceSlotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRequestId")
                        .IsUnique();

                    b.HasIndex("ServiceSlotId");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.AppointmentSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BookedSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("GovernmentServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("SlotDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAdminId");

                    b.HasIndex("GovernmentServiceId");

                    b.ToTable("AppointmentSlots");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRequestId")
                        .HasDatabaseName("IX_Attachments_ServiceRequestId");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("GovernmentEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("GovernmentEntityId", "IsActive")
                        .HasDatabaseName("IX_Branches_EntityId_Active")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.Citizen", b =>
                {
                    b.Property<string>("NationalNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NationalNumber");

                    b.ToTable("Citizens", (string)null);

                    b.HasData(
                        new
                        {
                            NationalNumber = "01100000003",
                            Address = "اللاذقية - المشروع الأول",
                            BirthDate = new DateOnly(2000, 1, 15),
                            Email = "yassin@example.com",
                            FatherName = "عمر",
                            FirstName = "ياسين",
                            Gender = "ذكر",
                            LastName = "الكردي",
                            MotherName = "ليلى"
                        },
                        new
                        {
                            NationalNumber = "01200000002",
                            Address = "دمشق - المزة",
                            BirthDate = new DateOnly(1998, 11, 22),
                            Email = "sara@example.com",
                            FatherName = "محمود",
                            FirstName = "سارة",
                            Gender = "أنثى",
                            LastName = "الأحمد",
                            MotherName = "مريم"
                        },
                        new
                        {
                            NationalNumber = "02100000001",
                            Address = "حلب - حي الفرقان",
                            BirthDate = new DateOnly(1995, 5, 10),
                            Email = "ahmed@example.com",
                            FatherName = "محمد",
                            FirstName = "أحمد",
                            Gender = "ذكر",
                            LastName = "المنصور",
                            MotherName = "فاطمة"
                        },
                        new
                        {
                            NationalNumber = "02250150972",
                            Address = "حلب - الشيخ مقصود",
                            BirthDate = new DateOnly(2002, 12, 29),
                            Email = "basharhannan400@gmail.com",
                            FatherName = "عماد",
                            FirstName = "بشار",
                            Gender = "ذكر",
                            LastName = "حنان",
                            MotherName = "فريدة"
                        });
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.CitizenPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("CitizenNationalNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CitizenNationalNumber")
                        .HasDatabaseName("IX_CitizenPhones_NationalNumber");

                    b.ToTable("CitizenPhones", (string)null);
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.CriminalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("CitizenNationalNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CrimeDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateOnly>("JudgmentDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CitizenNationalNumber")
                        .HasDatabaseName("IX_CriminalRecords_NationalNumber");

                    b.HasIndex("CitizenNationalNumber", "IsActive")
                        .HasDatabaseName("IX_CriminalRecords_NationalNumber_Active")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("CriminalRecords", (string)null);
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.FAQ", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "DisplayOrder")
                        .HasDatabaseName("IX_FAQ_Active_Order")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("FAQ", (string)null);
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.GovernmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("GovernmentEntities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Ministry of Interior",
                            IsActive = true,
                            Name = "وزارة الداخلية"
                        });
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.GovernmentService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("GovernmentEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Requirements")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GovernmentEntityId")
                        .HasDatabaseName("IX_GovernmentServices_EntityId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_GovernmentServices_IsActive")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("GovernmentServices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "خدمة تجديد جواز السفر منتهي الصلاحية",
                            GovernmentEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Name = "تجديد جواز السفر",
                            Requirements = "صورة شخصية + جواز السفر القديم + إثبات السكن",
                            ServiceFee = 150.00m,
                            ServiceType = 1
                        });
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead", "CreatedAt")
                        .HasDatabaseName("IX_Notifications_UserId_IsRead_CreatedAt")
                        .HasFilter("[IsRead] = 0");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.OtpVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("TempEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TempPasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TempPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NationalNumber", "IsUsed", "ExpiresAt")
                        .HasDatabaseName("IX_OtpVerifications_NationalNumber_Active");

                    b.ToTable("OtpVerifications", (string)null);
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.RequestAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("ServiceRequestId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_RequestAuditLogs_RequestId_CreatedAt");

                    b.ToTable("RequestAuditLogs", (string)null);
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.ServiceFieldOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("OptionLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ServiceFormFieldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServiceFormFieldId", "OptionValue")
                        .IsUnique()
                        .HasDatabaseName("IX_ServiceFieldOptions_FieldId_Value");

                    b.HasIndex("ServiceFormFieldId", "IsActive", "DisplayOrder")
                        .HasDatabaseName("IX_ServiceFieldOptions_FieldId_Active_Order")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("ServiceFieldOptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-0001-0001-0001-000000000001"),
                            DisplayOrder = 1,
                            IsActive = true,
                            OptionLabel = "أعزب/عزباء",
                            OptionValue = "single",
                            ServiceFormFieldId = new Guid("33333333-0001-0001-0001-000000000009")
                        },
                        new
                        {
                            Id = new Guid("44444444-0001-0001-0001-000000000002"),
                            DisplayOrder = 2,
                            IsActive = true,
                            OptionLabel = "متزوج/متزوجة",
                            OptionValue = "married",
                            ServiceFormFieldId = new Guid("33333333-0001-0001-0001-000000000009")
                        },
                        new
                        {
                            Id = new Guid("44444444-0001-0001-0001-000000000003"),
                            DisplayOrder = 3,
                            IsActive = true,
                            OptionLabel = "مطلق/مطلقة",
                            OptionValue = "divorced",
                            ServiceFormFieldId = new Guid("33333333-0001-0001-0001-000000000009")
                        },
                        new
                        {
                            Id = new Guid("44444444-0001-0001-0001-000000000004"),
                            DisplayOrder = 4,
                            IsActive = true,
                            OptionLabel = "أرمل/أرملة",
                            OptionValue = "widowed",
                            ServiceFormFieldId = new Guid("33333333-0001-0001-0001-000000000009")
                        });
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.ServiceFormField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("GovernmentServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HelpText")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ValidationRules")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GovernmentServiceId", "FieldName")
                        .IsUnique()
                        .HasDatabaseName("IX_ServiceFormFields_ServiceId_FieldName");

                    b.HasIndex("GovernmentServiceId", "IsActive", "DisplayOrder")
                        .HasDatabaseName("IX_ServiceFormFields_ServiceId_Active_Order")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("ServiceFormFields", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-0001-0001-0001-000000000001"),
                            DisplayOrder = 1,
                            FieldName = "fullName",
                            FieldType = "text",
                            GovernmentServiceId = new Guid("22222222-2222-2222-2222-222222222222"),
                            HelpText = "يجب أن يطابق الاسم المسجل في الهوية الوطنية",
                            IsActive = true,
                            IsRequired = true,
                            Label = "الاسم الكامل",
                            Placeholder = "أدخل اسمك الرباعي كما في الهوية",
                            ValidationRules = "{\"minLength\":3,\"maxLength\":100}"
                        },
                        new
                        {
                            Id = new Guid("33333333-0001-0001-0001-000000000002"),
                            DisplayOrder = 2,
                            FieldName = "nationalNumber",
                            FieldType = "text",
                            GovernmentServiceId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            IsRequired = true,
                            Label = "رقم الهوية الوطنية",
                            Placeholder = "1234567890",
                            ValidationRules = "{\"length\":10,\"pattern\":\"^[0-9]{10}$\"}"
                        },
                        new
                        {
                            Id = new Guid("33333333-0001-0001-0001-000000000003"),
                            DisplayOrder = 3,
                            FieldName = "currentPassportNumber",
                            FieldType = "text",
                            GovernmentServiceId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            IsRequired = true,
                            Label = "رقم جواز السفر الحالي",
                            Placeholder = "ABC123456",
                            ValidationRules = "{\"pattern\":\"^[A-Z]{3}[0-9]{6}$\",\"customMessage\":\"يجب أن يكون رقم الجواز بصيغة ABC123456\"}"
                        },
                        new
                        {
                            Id = new Guid("33333333-0001-0001-0001-000000000004"),
                            DisplayOrder = 4,
                            FieldName = "phoneNumber",
                            FieldType = "tel",
                            GovernmentServiceId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            IsRequired = true,
                            Label = "رقم الجوال",
                            Placeholder = "0501234567",
                            ValidationRules = "{\"pattern\":\"^05[0-9]{8}$\"}"
                        },
                        new
                        {
                            Id = new Guid("33333333-0001-0001-0001-000000000005"),
                            DisplayOrder = 5,
                            FieldName = "email",
                            FieldType = "email",
                            GovernmentServiceId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            IsRequired = true,
                            Label = "البريد الإلكتروني",
                            Placeholder = "example@email.com",
                            ValidationRules = "{\"pattern\":\"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\\\.[a-zA-Z]{2,}$\"}"
                        },
                        new
                        {
                            Id = new Guid("33333333-0001-0001-0001-000000000006"),
                            DisplayOrder = 6,
                            FieldName = "personalPhoto",
                            FieldType = "file",
                            GovernmentServiceId = new Guid("22222222-2222-2222-2222-222222222222"),
                            HelpText = "صورة بخلفية بيضاء، مقاس 4×6 سم",
                            IsActive = true,
                            IsRequired = true,
                            Label = "صورة شخصية حديثة",
                            Metadata = "{\"accept\":\".jpg,.jpeg,.png\",\"maxSizeMB\":5}",
                            ValidationRules = "{\"maxSize\":5242880,\"allowedTypes\":[\"image/jpeg\",\"image/png\"]}"
                        },
                        new
                        {
                            Id = new Guid("33333333-0001-0001-0001-000000000007"),
                            DisplayOrder = 7,
                            FieldName = "currentAddress",
                            FieldType = "textarea",
                            GovernmentServiceId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            IsRequired = true,
                            Label = "العنوان الحالي",
                            Placeholder = "أدخل عنوانك بالتفصيل",
                            ValidationRules = "{\"minLength\":10,\"maxLength\":200}"
                        },
                        new
                        {
                            Id = new Guid("33333333-0001-0001-0001-000000000008"),
                            DisplayOrder = 8,
                            FieldName = "preferredPickupDate",
                            FieldType = "date",
                            GovernmentServiceId = new Guid("22222222-2222-2222-2222-222222222222"),
                            HelpText = "سيتم إشعارك بالموعد النهائي خلال 48 ساعة",
                            IsActive = true,
                            IsRequired = true,
                            Label = "تاريخ الاستلام المفضل",
                            ValidationRules = "{\"minDate\":\"today+7\",\"maxDate\":\"today+30\"}"
                        },
                        new
                        {
                            Id = new Guid("33333333-0001-0001-0001-000000000009"),
                            DisplayOrder = 9,
                            FieldName = "maritalStatus",
                            FieldType = "select",
                            GovernmentServiceId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            IsRequired = true,
                            Label = "الحالة الاجتماعية"
                        });
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.ServiceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid?>("AppointmentSlotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GovernmentServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProcessingNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentSlotId");

                    b.HasIndex("BranchId");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_ServiceRequests_ReferenceNumber");

                    b.HasIndex("GovernmentServiceId", "SubmissionDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ServiceRequests_ServiceId_SubmissionDate");

                    b.HasIndex("Status", "SubmissionDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ServiceRequests_Status_SubmissionDate");

                    b.HasIndex("UserId", "SubmissionDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ServiceRequests_UserId_SubmissionDate");

                    b.ToTable("ServiceRequests", (string)null);
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.ServiceSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(0)");

                    b.Property<Guid>("GovernmentServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(0)");

                    b.HasKey("Id");

                    b.HasIndex("GovernmentServiceId", "Date")
                        .HasDatabaseName("IX_ServiceSlots_ServiceId_Date");

                    b.ToTable("ServiceSlots", (string)null);
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NationalNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_NationalNumber");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_PhoneNumber");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Wallets_UserId");

                    b.ToTable("Wallets", (string)null);
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("ServiceRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRequestId");

                    b.HasIndex("WalletId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_WalletTransactions_WalletId_CreatedAt");

                    b.ToTable("WalletTransactions", (string)null);
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("EGovServices.Domain.Entities.ServiceRequest", "ServiceRequest")
                        .WithOne("Appointment")
                        .HasForeignKey("EGovServices.Domain.Entities.Appointment", "ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EGovServices.Domain.Entities.ServiceSlot", "ServiceSlot")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceRequest");

                    b.Navigation("ServiceSlot");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.AppointmentSlot", b =>
                {
                    b.HasOne("EGovServices.Domain.Entities.User", "CreatedByAdmin")
                        .WithMany()
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGovServices.Domain.Entities.GovernmentService", "GovernmentService")
                        .WithMany()
                        .HasForeignKey("GovernmentServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByAdmin");

                    b.Navigation("GovernmentService");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("EGovServices.Domain.Entities.ServiceRequest", "ServiceRequest")
                        .WithMany("Attachments")
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.Branch", b =>
                {
                    b.HasOne("EGovServices.Domain.Entities.GovernmentEntity", "GovernmentEntity")
                        .WithMany("Branches")
                        .HasForeignKey("GovernmentEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GovernmentEntity");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.CitizenPhone", b =>
                {
                    b.HasOne("EGovServices.Domain.Entities.Citizen", "Citizen")
                        .WithMany("Phones")
                        .HasForeignKey("CitizenNationalNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.CriminalRecord", b =>
                {
                    b.HasOne("EGovServices.Domain.Entities.Citizen", "Citizen")
                        .WithMany()
                        .HasForeignKey("CitizenNationalNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.GovernmentService", b =>
                {
                    b.HasOne("EGovServices.Domain.Entities.GovernmentEntity", "GovernmentEntity")
                        .WithMany("Services")
                        .HasForeignKey("GovernmentEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GovernmentEntity");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.Notification", b =>
                {
                    b.HasOne("EGovServices.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.RequestAuditLog", b =>
                {
                    b.HasOne("EGovServices.Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId");

                    b.HasOne("EGovServices.Domain.Entities.ServiceRequest", "ServiceRequest")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.ServiceFieldOption", b =>
                {
                    b.HasOne("EGovServices.Domain.Entities.ServiceFormField", "ServiceFormField")
                        .WithMany("Options")
                        .HasForeignKey("ServiceFormFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceFormField");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.ServiceFormField", b =>
                {
                    b.HasOne("EGovServices.Domain.Entities.GovernmentService", "GovernmentService")
                        .WithMany("FormFields")
                        .HasForeignKey("GovernmentServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GovernmentService");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.ServiceRequest", b =>
                {
                    b.HasOne("EGovServices.Domain.Entities.AppointmentSlot", "AppointmentSlot")
                        .WithMany("Requests")
                        .HasForeignKey("AppointmentSlotId");

                    b.HasOne("EGovServices.Domain.Entities.Branch", "Branch")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EGovServices.Domain.Entities.GovernmentService", "GovernmentService")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("GovernmentServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGovServices.Domain.Entities.User", "User")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppointmentSlot");

                    b.Navigation("Branch");

                    b.Navigation("GovernmentService");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.ServiceSlot", b =>
                {
                    b.HasOne("EGovServices.Domain.Entities.GovernmentService", "GovernmentService")
                        .WithMany("ServiceSlots")
                        .HasForeignKey("GovernmentServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GovernmentService");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.User", b =>
                {
                    b.HasOne("EGovServices.Domain.Entities.Citizen", "Citizen")
                        .WithOne("User")
                        .HasForeignKey("EGovServices.Domain.Entities.User", "NationalNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("EGovServices.Domain.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("EGovServices.Domain.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("EGovServices.Domain.Entities.ServiceRequest", "ServiceRequest")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EGovServices.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceRequest");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.AppointmentSlot", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.Branch", b =>
                {
                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.Citizen", b =>
                {
                    b.Navigation("Phones");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.GovernmentEntity", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.GovernmentService", b =>
                {
                    b.Navigation("FormFields");

                    b.Navigation("ServiceRequests");

                    b.Navigation("ServiceSlots");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.ServiceFormField", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.ServiceRequest", b =>
                {
                    b.Navigation("Appointment");

                    b.Navigation("Attachments");

                    b.Navigation("AuditLogs");

                    b.Navigation("WalletTransactions");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.ServiceSlot", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("ServiceRequests");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("EGovServices.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
